# CC = gcc
# CFLAGS = -Wall -Wextra -g

# # The name of the final executable
# TARGET = avg3

# # Find all .c files in the current directory
# SRCS = $(wildcard *.c)
# # Replace the .c extension with .o to create a list of object files
# OBJS = $(SRCS:.c=.o)

# all: $(TARGET)

# $(TARGET): $(OBJS)
# 	$(CC) $(CFLAGS) -o $@ $^

# %.o: %.c
# 	$(CC) $(CFLAGS) -c $< -o $@

# clean:
# 	rm -f $(OBJS) $(TARGET)

# .PHONY: all clean
